#import "@preview/arkheion:0.1.1": arkheion, arkheion-appendices

#show: arkheion.with(
  title: "From Theory to Therapy: Evaluating AI-Generated Psychotherapy Notes in Real Clinical Practice",
  authors: (
    (name: "Harrys Kavan", email: "ir241506@fhstp.ac.at", affiliation: "FH St. Pölten University of Applied Sciences"),
  ),
  abstract: [
    Psychologists at an Austrian outpatient anxiety clinic are evaluating whether locally deployed AI can draft psychotherapy notes that meet professional standards. The trial embeds automation directly in routine documentation, comparing machine-generated and human notes across blinded review and contextual self-assessment. The study gauges clinical quality, user acceptance, and workflow impact while preserving data privacy.
  ],
  keywords: ("psychotherapy", "documentation", "artificial intelligence", "clinical evaluation"),
  date: "2025-10-07",
)

Disclosure: I used generative artificial intelligence tools to proof-read and polish this paper; all research and conclusions are my own.

#show link: underline
#set cite(style: "ieee")

= From Theory to Therapy: Evaluating AI-Generated Psychotherapy Notes in Real Clinical Practice

== Main Text
Artificial intelligence has long been expected to ease the burden of clinical documentation, yet most studies evaluate its performance in laboratory or retrospective settings. In psychotherapy, where subtle language and interpersonal nuance matter, such systems must be tested under the conditions in which they would actually be used. The current study, conducted at FH St. Pölten in collaboration with the University of Vienna and the Phobius outpatient clinic, investigates whether AI-drafted therapy notes can meet professional quality expectations in real practice.

The project examines everyday documentation tasks, in which therapists record short notes after or during each session. These notes help structure treatment, preserve continuity, and communicate with colleagues. The research question is simple but crucial: can an AI system produce session summaries that psychologists judge to be sufficiently clear, accurate, and useful for clinical work? To answer this, the team designed a controlled yet ecologically valid evaluation procedure implemented directly at the clinic.

#figure(
  image("image.png", width: 80%),
  caption: [Study timeline overview with key milestones from pilot setup to analysis wrap-up.]
)

== Study Design
Each participating psychologist completes a structured two-hour evaluation session. In the first block, they review short notes from therapy sessions written either by colleagues or generated by a large local language model running on-site. They rate each note on a five-point scale that reflects overall clarity, completeness, and clinical usefulness. In the second block, they rate notes from their own sessions, drawing on their memory and full clinical context. This step replicates real-world conditions: a therapist judging whether an AI-generated summary captures what truly happened in the room. A short usability questionnaire concludes the session, gathering views on practicality and acceptance.

This three-block sequential design balances methodological control with realism. The first block provides a blind peer baseline, while the second captures contextual self-assessment, the primary endpoint for clinical acceptability. The third block collects qualitative feedback about workflow and implementation. This combination allows both rigorous measurement and direct insight into everyday feasibility.

== Ethical and Technical Safeguards
All data processing occurs within a secure, offline infrastructure at the clinic. Audio recordings and AI-generated drafts never leave this environment. Only anonymised numerical ratings are transferred to FH St. Pölten for analysis. This architecture ensures compliance with data protection regulations and maintains full control of clinical material. Clients and therapists give informed consent and may withdraw at any time.

The protocol follows principles of transparency and voluntary participation. It also applies safeguards against rating bias: evaluators are initially unaware of whether a note was written by a human or generated by AI, a procedure adapted from sequential unmasking techniques designed to reduce cognitive bias in expert judgment (Dror & Kukucka, 2021).

== Progress and Scope
As of October 2025, data collection is actively under way. Eight licensed clinical psychologists are participating, and 57 therapy sessions have already been recorded using standard digital equipment. Each session adds both human-written and AI-drafted notes to the evaluation pool. When the study reaches its target of about 300 recorded sessions, the researchers expect roughly 520 individual ratings. Statistical simulations show that this sample size provides > 98 % power to detect differences of half a point on the five-point quality scale. This ensures that even subtle performance gaps between AI and human notes can be reliably identified.

== Expected Outcomes
The primary analysis will test whether AI-generated notes are judged to be within half a point of human-written notes on the overall quality scale when rated with full clinical context. Because the five-point scale uses whole-number anchors, a 0.5 difference marks the threshold between clinically acceptable and unacceptable performance. Supporting analyses will examine rating consistency across therapists and evaluate how contextual knowledge influences perceptions of quality. Feasibility measures, such as completion rates and qualitative feedback, will indicate how well the workflow integrates into routine clinical practice.

Rather than aiming to replace clinicians' judgment, the study seeks to determine whether AI documentation can become a trustworthy assistant. If results confirm that locally deployed AI achieves clinically acceptable performance, it could help reduce documentation workload and free more time for direct patient interaction.

== Broader Significance
This project represents one of the first European attempts to evaluate generative AI for psychotherapy documentation directly within clinical operations. By embedding the evaluation in real therapy sessions and maintaining strict data protection, it demonstrates how ethical and technical requirements can coexist with innovation. The study also provides a reproducible framework for other clinics that wish to test AI tools safely, without transferring sensitive data to external systems.

Through its combination of scientific control and practical deployment, the work exemplifies how responsible AI research can move from theory to therapy. It aligns with European efforts to ensure that artificial intelligence in healthcare remains both effective and trustworthy.

== References
Stetson P. D., et al. (2012). Assessing Electronic Note Quality Using the Physician Documentation Quality Instrument (PDQI-9). *Applied Clinical Informatics*, 3(2), 164-174.

Dror I. E. & Kukucka J. (2021). Linear Sequential Unmasking-Expanded: A General Approach for Minimizing Bias. *Forensic Science International: Synergy*, 3, 100161.

Lakens D. (2022). Sample Size Justification. *Collabra: Psychology*, 8(1), 33267.

Contact: Harrys Kavan, FH St. Pölten University of Applied Sciences, Austria (#link("mailto:ir241506@fhstp.ac.at")[ir241506\@fhstp.ac.at])
